//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_MiddleLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8145/WebService1.asmx")]
        public string SMART_MiddleLayer_OCRInvoker_LocalIIS_WebService1 {
            get {
                return ((string)(this["SMART_MiddleLayer_OCRInvoker_LocalIIS_WebService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://BPMSERVER:8181/ws/InitBlueprismDataItemfromC")]
        public string SMART_MiddleLayer_BP_AutomationService_InitBlueprismDataItemfromCService {
            get {
                return ((string)(this["SMART_MiddleLayer_BP_AutomationService_InitBlueprismDataItemfromCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://auraportal.lateetud.com/WS/WS_OCR_File_Data_Sub.asmx")]
        public string SMART_MiddleLayer_SubmissionProcess_EM_WS_OCR_File_Data_Sub {
            get {
                return ((string)(this["SMART_MiddleLayer_SubmissionProcess_EM_WS_OCR_File_Data_Sub"]));
            }
        }
    }
}
